name: pa-applet
version: "0.1"
summary: pulse audio applet
description: |
    A dead simple pulse audio applet

confinement: strict
base: core18

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
    filesets:
      files-from-stage-packages-excluding-docs:
        - usr/*
        - bin/*
        - lib/*
        - -usr/share/doc/*
    stage:
      - $files-from-stage-packages-excluding-docs
  pa-applet:
    plugin: autotools
    source-type: git
    source: https://github.com/fernandotcl/pa-applet.git
    build-packages:
      - libglib2.0-dev
      - libgtk-3-dev
      - libnotify-dev
      - libpulse-dev
      - libx11-dev
      - gcc
      - make
    stage-packages:
      - libglib2.0-0
      - libgtk-3-0
      - libnotify4
      - libpulse0
      - pulseaudio
      - libx11-6
      - libpulse-mainloop-glib0
      - libgdk-pixbuf2.0-0
      - libcanberra-gtk-module
    filesets:
      files-from-stage-packages-excluding-docs:
        - usr/*
        - bin/*
        - lib/*
        - -usr/share/doc/*
    stage:
      - $files-from-stage-packages-excluding-docs
apps:
  pa-applet:
    command: desktop-launch $SNAP/bin/pa-applet
    environment:
      "LD_LIBRARY_PATH": "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
